config/routes.rb
PhPol::Application.routes.draw do
  devise_for :users, :controllers => {
    :omniauth_callbacks => "users/omniauth_callbacks",
    :registrations => "registrations"
  }

  root :to => "root#index"

  get '/listing', to: 'listing#index', as: :listing_index
  get '/listing/location', to: 'listing#location', as: :listing_location
  get '/listing/:id', to: 'listing#show', as: :listing
  get '/listing/:id/post/:cmt_id', to: 'listing#show_post', as: :listing_post
  post '/listing/:id/vote/:vote', to: 'listing#create_vote', as: :listing_vote_create
  post '/listing/:id/:career_id/image', to: 'listing#create_image', as: :listing_image_create
  post '/listing/location', to: 'listing#create_location_pref', as: :listing_locpref_create

  resources :comment, only: [:show, :create, :destroy]

  namespace :users do
    resources :profile, only: [:edit, :update, :show]
  end

  post 'util/municipal/:id', to: 'util#municipal', as: :util_municipal
  post 'util/pol/', to: 'util#politicians', as: :util_politicians
  get 'util/http_get/', to: 'util#http_get', as: :util_httpget

  

end

app/controllers/listing_controller.rb
class ListingController < ApplicationController
  helper_method :sort_column, :sort_direction

  # Controller that displays all Politicians
  def index
    params[:page] ||= 1
    @municipal_id = (params[:municipal] and !params[:municipal][:id].blank?) ? params[:municipal][:id] : ""
    @province_id = (params[:province] and !params[:province][:id].blank?) ? params[:province][:id] : ""

    # Retrieve info for dropdown
    @nationwide = Location.get_nationwide
    @provinces = Location.provinces.where('id != ?', @nationwide.id).collect {|p| [p.name.capitalize, p.id]}.insert(0, [@nationwide.name.capitalize, @nationwide.id])
    @municipals = Location.municipality(@province_id)

    # get Politicians based on their current career
    # -- we split these into two variables, one for pagination, one for looping thru
    #    all the records. This is necessary because all pagination gems gets confused
    #    if the query has groups/LEFT JOINs
    @careers = Career.current
      .select_title_heirarchy
      .with_loc_and_pol
      .search(params[:search])
      .in_municipal(@municipal_id)
      .in_province(@province_id)
      .page(params[:page])

    @careers_with_comments = @careers
      .order(sort_column + " " + sort_direction + ", politicians.id")
      .with_comments

  end

  # Displays one politician and all comments tied to him/her
  def show
    @page = (params.has_key?(:page) ? params[:page].to_i : 1)
    @politician = Politician.find(params[:id])
    @target_cmt_id = params[:cmt_id]

    @career = Career.with_loc_and_pol.where(politician_id: @politician.id).first

    @comment = Comment.new
    @new_image = PolImage.new

    if current_user.present?
      @user_votes = current_user.get_votes_of_pol(@politician.id)
    else
      @user_votes = []
    end

  end

  # Allow users to select province/location
  def location
    # Retrieve info for dropdown
    @nationwide = Location.get_nationwide
    #@provinces = Location.provinces.where('id != ?', @nationwide.id).order('denorm_sort').collect {|p| [p.name.capitalize, p.id]}.insert(0, [@nationwide.name.capitalize, @nationwide.id])
    @provinces = Location.provinces.where('id != ?', @nationwide.id).order('denorm_sort')

    # Retrieve previously selected locations
    @curr_locations = current_user.present? ? current_user.locations.pluck(:id) : []

    # Get all regions for the map display 
    @regions = Region.order('region_iso').all
  end

  # Display comments under one post
  def show_post
    @comment = Comment.find(params[:cmt_id])
  end

  # -- CUD Controllers -------------------------------------

  # Create vote for a comment
  def create_vote

    @comment = Comment.find(params[:id])

    if current_user.present?
      # upvote
      if params[:vote] == "1"
        # if user already upvoted, then 'unvote'
        if current_user.voted_up_on? @comment
          @comment.unliked_by current_user
        else
          @comment.liked_by current_user
        end

      # downvote
      else
        # if user already downvoted, then 'undownvote'
        if current_user.voted_down_on? @comment
          @comment.undisliked_by current_user
        else
          @comment.disliked_by current_user
        end
      end
    end

    if !@comment.user.nil?
      @comment.user.update_cache
    end
    @user_votes = current_user.get_votes_of_pol(@comment.commentable.politician.id)
  end

  # Upload image
  def create_image

    if current_user.present?
      @career = Career.find(params[:career_id])

      @image = PolImage.new
      @image.career = @career
      if params[:pol_image].has_key?(:remote_file_url) && !params[:pol_image][:remote_file_url].blank?
        puts "saving with remote_file_url"
        @image.remote_file_url = params[:pol_image][:remote_file_url]
      else
        puts "saving with file"
        @image.file = params[:pol_image][:file]
      end
      
      if @image.save
        flash[:notice] = "Photo uploaded successfully"
      else
        flash[:alert] = "Error: #{@image.errors.full_messages.join(",")}"
      end
    end

    redirect_to listing_path(params[:id])
  end

  # Set location
  def create_location_pref
    # if user signed up, save to db
    # if not, save to cookies

    if current_user.present?

      locations = Location.find(params[:prov])

      if current_user.locations.length > 0
        current_user.locations.delete_all
      end
      current_user.locations << locations

      flash[:notice] = "Locations added successfully"
    end

    redirect_to root_path
  end

  private
  def sort_column
    %w[locations.denorm_name politicians.first_name politicians.last_name title_heirarchy num_comments].include?(params[:sort]) ? params[:sort] : "title_heirarchy"
  end

  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
  end
end

app/helpers/listing_helper.rb
module ListingHelper
end

app/views/listing/_comments.html.erb
<%# Default local values %>
<% max_depth = local_assigns.fetch(:max_depth, 3) %>
<% target_comment = local_assigns.fetch(:target_comment, nil) %>
<% hide_lowscores = local_assigns.fetch(:hide_lowscores, true) %>
<% show_paginate = local_assigns.fetch(:show_paginate, true) %>
<% is_child = local_assigns.fetch(:is_child, false) %>
<% page_size = local_assigns.fetch(:page_size, 10) %>
<% page_number = local_assigns.fetch(:page_number, 1) %>
<% comment_hash = local_assigns.fetch(:comment_hash, @comment.hash_tree[@comment]) %>

<% if show_paginate %>
  <%= render partial: "listing/paginate", locals: { count: comment_hash.count, page_size: page_size, page_number: page_number } %>
<% end %>

<% comment_hash.each_pair do |cmt, child| %>
  <% if is_score_too_low(cmt) %>
      <ul id="cmt_<%= cmt.id %>" class="lowscore">
        <li>
          <span class="user"> (<%= cmt.username_display %>) </span>
          hidden due to too many downvotes
          <%= link_to "show", comment_path(cmt.id, hide_lowscores: 0), remote: true %>
        </li>
      </ul>
    <% else %>

      <div id="cmt_<%= cmt.id %>" class="row">
        <div class="col-sm-1 col-xs-2">
          <%= render partial: "listing/votes", locals: { cmt: cmt } %>
        </div>

        <% if cmt.has_image? %>
          <div class="col-sm-2 col-xs-4">
            <% if !cmt.pol_image.nil? %> <%= cl_image_tag cmt.pol_image.file_url(:medium), class: "img-responsive" %> <% end %>
            <% if !cmt.external_link.blank? && !cmt.external_link.image_url.blank? %> <img src="<%= cmt.external_link.image_url %>" class="img-responsive" /> <% end %>
          </div>
        <% end %>

        <div class="col-sm-9 col-xs-6">
          <h4>
              <%= cmt.pretty_title.try(:html_safe) %>
              <br/>
              <small>
                Posted by <%= cmt.user.nil? ? cmt.username_display : link_to(cmt.username_display, users_profile_path(cmt.user.id)) %>
                <span class="badge"><%= cmt.user.cached_score if !cmt.user.nil? %></span>
                on <%= cmt.created_at_pretty %>
              </small>
              <br/>
          </h4>


          <% if user_signed_in? %>
            <%= link_to "#", onclick: "cmt_show_and_ckedify(#{cmt.id}, 1); return false;", class: "reply" do %>
              <span class="glyphicon glyphicon-share-alt"></span> reply
            <% end %>
            <%= render partial: "listing/new_comment", locals: { comment: nil, politician: @comment.commentable.politician, c: @comment.commentable, cmt: cmt, visible: false } %>
          <% end %>

          <p> <%= cmt.comment.try(:html_safe)%> </p>

          <% if !child.blank? %>
            <% if max_depth-1 > 0 || max_depth < 0 %>
              <%= render partial: "listing/comments", locals: { is_child: true, comment: @comment, comment_hash: child, max_depth: max_depth - 1, show_paginate: false} %>
            <% else %>
              <%= link_to "load more replies (#{pluralize(child.length, 'reply', 'replies')})", comment_path(cmt.id), remote: true %>
            <% end %>
          <% end %>

        </div>


      </div>

    <% end %>
<% end %>

<%
=begin
%>
<div class="<%= is_child ? 'row_striped_child' : 'row_striped' %>">
<% posts[:hash].each_pair do |cmt, child| %>
  <% if hide_lowscores && is_score_too_low(cmt) %>
    <ul id="cmt_<%= cmt.id %>" class="lowscore">
      <li>
        <span class="user"> (<%= cmt.username_display %>) </span>
        hidden due to too many downvotes
        <%= link_to "show", comment_path(cmt.id, hide_lowscores: 0), remote: true %>
      </li>
    </ul>
  <% else %>

    <div id="cmt_<%= cmt.id %>" class="row" style="margin: 20px 0;">

      <% if is_child %>
        <div class="col-md-2"></div>
      <% else %>
        <div class="col-md-2">
          <% if !cmt.pol_image.nil? %> <%= cl_image_tag cmt.pol_image.file_url(:medium), class: "img-responsive" %> <% end %>
          <% if !cmt.external_link.blank? && !cmt.external_link.image_url.blank? %> <img src="<%= cmt.external_link.image_url %>" class="img-responsive" /> <% end %>
        </div>
      <% end %>

      <div class="col-md-9">
        <p>
        <% if cmt.external_link.blank? %>
          <%= cmt.comment.try(:html_safe)%>
        <% else %>
            <p>
              <%= cmt.external_link.title.try(:html_safe) %>
              <br/><a class='small' href='<%= cmt.external_link.link_url %>'><%= cmt.external_link.link_url %></a>
            </p>

            <p><%= cmt.external_link.description.try(:html_safe) %></p>
        <% end %>
        </p>

        <h6 style="margin:2em 0 0 0;"> Posted by <%= cmt.user.nil? ? cmt.username_display : link_to(cmt.username_display, users_profile_path(cmt.user.id)) %>
          <span class="badge"><%= cmt.user.cached_score if !cmt.user.nil? %></span>
          <br/><small><%= cmt.created_at_pretty %></small>
        </h6><br/>

        <%= link_to "reply", "#", onclick: "cmt_show_and_ckedify(#{cmt.id}, 1); return false;", class: "reply" %>
        <div class="fb-share-button" data-href="<%= listing_path(career.politician.id, cmt_id: cmt.id) %>" data-type="button"></div>
        <% if user_signed_in? %>
          <%= render partial: "listing/new_comment", locals: { comment: Comment.new, politician: career.politician, c: career, cmt: cmt, visible: false } %>
        <% end %>

      </div>

      <div class="col-md-1">
        <%= render partial: "listing/votes", locals: { cmt: cmt } %>
      </div>

    </div>

    <% if !child.blank? %>
      <% if max_depth-1 > 0 || max_depth < 0 %>
        <%= render partial: "listing/comments", locals: { is_child: true, career: career, posts: { count: child.length, hash: child, page_size: posts[:page_size], page_number: posts[:page_number] }, max_depth: max_depth - 1, show_paginate: false} %>
      <% else %>
        <%= link_to "load more replies (#{pluralize(child.length, 'reply', 'replies')})", comment_path(cmt.id), remote: true %>
      <% end %>
    <% end %>

  <% end %>
<% end %>

</div>
<%
=end
%>


<% if show_paginate %>
  <%= render partial: "listing/paginate", locals: { count: comment_hash.count, page_size: page_size, page_number: page_number } %>
<% end %>

app/views/listing/_new_comment.html.erb
<% if false && defined?(header_label) %>
  <h3 class="tab-header">
    <% if defined?(header_icon) %>
      <i class="fa <%= header_icon %>"></i>
    <% end %>
    <%= header_label %>
<%
=begin %>
     <span class="glyphicon glyphicon-plus"></span> <%= defined?(header_label) ? header_label : "Post Comment" %>
<%
=end %>
  </h3>
<% end %>

<div id="new_cmt_<%= cmt ? cmt.id : 'new' %>" class="cmt-form" style="<%= 'display: none;' if !visible %>">
  <%= form_for [comment,PolImage.new], url: comment_index_path, html: { id: "new_comment_#{ cmt ? cmt.id : '' }", multipart: true, style: "margin-top: 30px;" } do |f| %>
    <div class="comment_errors"></div>

    <ul class="nav nav-tabs">
      <li class="active">
        <a href="#link<%= cmt ? cmt.id : 'new' %>" data-toggle="tab">
          <% if defined?(header_icon) %> <i class="fa <%= header_icon %>"></i> <% end %>
          <%= (defined?(header_label) ? header_label : "Create post").titleize %> using link
        </a>
      </li>
      <li>
        <a href="#photo<%= cmt ? cmt.id : 'new' %>" data-toggle="tab">
          <% if defined?(header_icon) %> <i class="fa <%= header_icon %>"></i> <% end %>
          <%= (defined?(header_label) ? header_label : "Create post").titleize %> using photo
        </a>
      </li>
    </ul>

    <!-- Tab panes -->
    <div class="tab-content">
      <div class="tab-pane active form-horizontal" id="link<%= cmt ? cmt.id : 'new' %>">
        <div class="form-group">
          <label for="link_url<%= cmt ? "_" + cmt.id.to_s : '' %>" class="control-label col-sm-2">Link</label>
          <div class="col-sm-10">
            <%= text_field_tag :link_url, '', id: "link_url#{ cmt ? "_" + cmt.id.to_s : '' }", class: "form-control", placeholder: "Paste the url here" %>
          </div>
        </div>
        <div id="div_prev<%= cmt ? "_" + cmt.id.to_s : '' %>" class="form-group container hidden"></div>

          <script type='text/javascript'>
            function lp<%= cmt ? "_" + cmt.id.to_s : '' %>(elem) {
              $(elem).addClass('loading');
              var div = $("#div_prev<%= cmt ? "_" + cmt.id.to_s : '' %>");
              div.removeClass('hidden');
              div.html('<span>Loading...</span>');
              // parse external url
              var url = '<%= CGI.unescape util_httpget_path %>?u=' + $(elem).val();
              $.get(url, function(data) {
                <%# Create preview using json object %>
                <%# [images, title, desc, link] %>

                div.html("<div class='col-sm-2'></div>");
                if ( data.images.length && data.images[0].length ) {
                  div.append("<div class='col-sm-2'><img src='" + data.images[0] + "' class='img-responsive' /></div>");
                } else {
                  div.append("<div class='col-sm-2'></div>");
                }
                div.append("<div class='col-sm-8'><h3>" + data.title + "</h3><p>" + data.desc + "<br/><a class='link_url' href='" + data.link + "'>read more</a></p>");

                $("#cmt_title<%= cmt ? "_" + cmt.id.to_s : '' %>").val("Link - " + data.title);

                $(elem).removeClass('loading');

              }).fail(function() {
                div.html('<div>Failed to load, please check your URL</div>');
                $(elem).removeClass('loading');
              });
            }

            bind_on_keyup("#link_url<%= cmt ? "_" + cmt.id.to_s : '' %>", lp<%= cmt ? "_" + cmt.id.to_s : '' %>);

          </script>
      </div>
      <div class="tab-pane" id="photo<%= cmt ? cmt.id : 'new' %>">
        <%= f.hidden_field :file_cache %>
        <%= f.file_field :file %>
      </div>
    </div>


    <%= hidden_field_tag :career_id, c.id %>
    <% if cmt %>
      <%= hidden_field_tag :parent_comment_id, cmt.id %>
    <% end %>

    <div class="clearfix"> </div>

    <div class="form-horizontal cmt-form-body">
      <div class="form-group">
        <label for="cmt_title" class="control-label col-sm-2">Title</label>
        <div class="col-sm-10"><%= text_field_tag :cmt_title, '', id: "cmt_title#{ cmt ? "_" + cmt.id.to_s : '' }", class: "form-control", placeholder: "Title" %></div>
      </div>

      <div class="form-group">
        <label for="cmt_title" class="control-label col-sm-2">Comment</label>
        <div class="col-sm-10">
          <%= f.text_area :comment, cols: 80, rows: 8, id: "txt_comment#{ cmt ? "_" + cmt.id.to_s : '' }", class: "comment_body #{'ph_ckeditor' if visible}" %>
        </div>
      </div>

      <div class="form-group">
        <div class="col-sm-2"></div>
        <div class="col-sm-10">
          <%= f.submit "Post" %>
        </div>
      </div>
    </div>


  <% end %>
</div>

app/views/listing/_paginate.html.erb
<%
  # Required variables:
  # count - total number of rows
  # page_size - page size
  # page_number - current page

  # Set variables
  last_page = (Float(count.nil? ? 0 : count) / page_size).ceil
%>

<% if last_page > 1 %>
<ul class="pagination">
  <% if page_number > 1 %>
    <li> <a href="?page=<%= page_number - 1%>" rel="prev">&laquo;</a> </li>
  <% else %>
    <li class="disabled"> <a rel="prev">&laquo;</a> </li>
  <% end %>

<% (1..last_page).each do |i| %>
  <% if page_number == i %>
    <li class='active'> <a href='#'><%= i %> </a></li>
  <% else %>
    <li> <a href="?page=<%= i %>"><%= i %></a> </li>
  <% end %>
<% end %>

<% if page_number >= last_page %>
  <li class="disabled"> <a rel="prev">&raquo;</a> </li>
<% else %>
  <li> <a href="?page=<%= page_number + 1%>" rel="prev">&raquo;</a> </li>
<% end %>

</ul>
<% end %>

app/views/listing/_photos.html.erb
<div id="photos_<%= c.id %>" class="photo_list">
  <% c.pol_image.each do |img| %>
    <%= image_tag img.file_url(:medium), id: img.id %>
  <% end %>
</div>

app/views/listing/_votes.html.erb
<div id="vote_<%= cmt.id %>" class="text-center text-muted votebox">
  <div>
      <% if !user_signed_in? %>
        <a class='disabled text-muted' title='You need to sign in to vote'><span class="glyphicon glyphicon-chevron-up"></span></a>
      <% elsif user_signed_in? && cmt.user == current_user %>
        <a class='disabled text-muted' title='You cannot vote for your own posts'><span class="glyphicon glyphicon-chevron-up"></span></a>
      <% else %>
        <%= link_to listing_vote_create_path(cmt, 1), remote: true, method: "post", class: "#{ (@user_votes.nil? || @user_votes.select { |cid, vote_flag| cid == cmt.id }.empty? || !@user_votes.select { |cid, vote_flag| cid == cmt.id }[0][1] ) ? "" : "text-primary" }", title: "Upvote" do %>
          <span class="glyphicon glyphicon-chevron-up"></span>
        <% end %>
      <% end %>
  </div>

  <div>
  <%= cmt.cached_votes_score %>
  </div>

  <div>
      <% if !user_signed_in? %>
        <a class='disabled text-muted' title='You need to sign in to vote'><span class="glyphicon glyphicon-chevron-down"></span></a>
      <% elsif user_signed_in? && cmt.user == current_user %>
        <a class='disabled text-muted' title='You cannot vote for your own posts'><span class="glyphicon glyphicon-chevron-down"></span></a>
      <% else %>
        <%= link_to listing_vote_create_path(cmt, 0), remote: true, method: "post", class: "#{ (@user_votes.nil? || @user_votes.select { |cid, vote_flag| cid == cmt.id }.empty? || @user_votes.select { |cid, vote_flag| cid == cmt.id }[0][1]) ? "" : "text-warning" }", title: "Downvote" do %>
          <span class="glyphicon glyphicon-chevron-down"></span>
        <% end %>
      <% end %>
  </div>
</div>

app/views/listing/create_vote.js.erb
<%# Update Votes widget %>
$("#vote_<%= @comment.id %>").replaceWith("<%= escape_javascript( render(partial: "votes", locals: { cmt: @comment }) ) %>");

app/views/listing/index.html.erb
<%= title "All Politicians" %>

<%= form_tag listing_index_path, :method => 'get', :id => "listing_search" do %>
  <%= hidden_field_tag :direction, params[:direction] %>
  <%= hidden_field_tag :sort, params[:sort] %>

  <div class="div_form">
    <div class="title"> Search </div>
    <div class="field_line">
      <%= label_tag(:search, 'Keyword') %>
      <%= text_field_tag :search, params[:search] %>
    </div>
    <div class="field_line">
      <%= label(:province, :id, "Location") %>
      <%= select("province", "id", @provinces, { include_blank: "-- select province --", selected: @province_id } ) %>
      <%= select("municipal", "id", @municipals ? @municipals.collect {|p| [p.name, p.id]} : {}, { include_blank: "-- select municipal --", selected: @municipal_id } ) %>

      <script type="text/javascript">
        $('#province_id').change(function() {
          var url = '<%= CGI.unescape util_municipal_url("{id}") %>'.replace('{id}',$(this).val());
          $.post(url, function(data) {
            var sub = $('#municipal_id').find('option').remove().end().append('<option value="">-- select municipal --</option>');
            $.each( data, function(i, item) {
              sub.append('<option value="' + item.id + '">' + item.name + '</option>');
            });
          });
        });
      </script>
    </div>

    <div class="field_line">
      <%= submit_tag "Search", :name => nil %>
    </div>
  </div>
<% end %>

<%= paginate @careers %>
<table class="tbl_listing" style="width: 100%;">
  <tr>
    <th><%= sortable "num_comments", "# Comments" %></th>
    <th><%= sortable "title_heirarchy", "Title" %></th>
    <th><%= sortable "politicians.first_name", "Name" %></th>
    <th><%= sortable "locations.denorm_name", "Location" %></th>
    <th></th>
  </tr>
  <% @careers_with_comments.each do |c| %>
  <tr>
    <td align='center'> <%= c.num_comments %> </td>
    <td align='center'> <%= c.title %> </td>
    <td> <%= c.politician_first_name.blank? ? "" : c.politician_first_name.capitalize %> <%= c.politician_nickname.blank? ? "" : "'#{c.politician_nickname.upcase}'" %> <%= c.politician_last_name.capitalize %> </td>
    <td align='center'> <%= c.location_denorm_name %> </td>
    <td> <%= link_to 'Details', listing_path(c.politician_id) %></td>
  </tr>
  <% end %>
</table>
<%= paginate @careers %>

app/views/listing/show.html.erb
<% title (@career.title.titleize + " - " + @politician.full_name.titleize) %>


  <ol class="breadcrumb">
    <li><%= @career.title.titleize %></li>
    <li><%= @career.location.denorm_name.titleize %></li>
  </ol>


  <div class="container">
    <h3 class="tab-header">Posts</h3>
    <div id="all_cmt_<%= @career.id %>" class="career row">

      <% if !@target_cmt_id.blank? %>
        <div class="notif_header">
          Showing single post
          <%= link_to "show other posts", listing_path(@politician.id) %>
        </div>
      <% end %>

      <% @career.comments.posts.order("cached_votes_score desc").each do |cmt| %>

        <% if is_score_too_low(cmt) %>
<%
=begin
%>
            <ul id="cmt_<%= cmt.id %>" class="lowscore">
              <li>
                <span class="user"> (<%= cmt.username_display %>) </span>
                hidden due to too many downvotes
                <%= link_to "show", comment_path(cmt.id, hide_lowscores: 0), remote: true %>
              </li>
            </ul>
<%
=end %>
          <% else %>

            <div id="cmt_<%= cmt.id %>" class="col-md-3 col-sm-6 post-box">
              <div class="post-box-img" href="<%= listing_post_url(@career.politician.id, cmt.id) %>" style="background-image: url('<%= !cmt.pol_image.nil? ? cmt.pol_image.file_url(:medium) : ((!cmt.external_link.blank? && !cmt.external_link.image_url.blank?) ? cmt.external_link.image_url : ""  ) %>');">
                <%= render partial: "listing/votes", locals: { cmt: cmt } %>
              </div>
              <div class="subbox">
                  <%= link_to trunc(cmt.pretty_title, 40).try(:html_safe), listing_post_url(@career.politician.id, cmt.id) %>
                  <br/>
                  <small>
                    by <%= cmt.user.nil? ? cmt.username_display : link_to(cmt.username_display, users_profile_path(cmt.user.id)) %>
                    <br/>
                    <a href="<%= listing_post_url(cmt.commentable.politician.id, cmt.id) %>" title="<%= pluralize cmt.children.count, "comment" %>">
                      <span class="glyphicon glyphicon-comment"></span> <%= cmt.children.count %>
                    </a>
                    <div class="fb-share-button" data-href="<%= listing_post_url(@career.politician.id, cmt.id) %>" data-type="icon" title="Post on Facebook"></div>
                  </small>
              </div>
              
            </div>
          <% end %>
      <% end %>

      <%# render partial: "comments", locals: { career: c, posts: @career.posts(target_cmt_id = @target_cmt_id, page_number = @page) } %>
    </div>

    <% if user_signed_in? %>
      <%= render partial: "new_comment", locals: { comment: @comment, politician: @politician, c: @career, cmt: nil, visible: true, header_label: "Submit Post", header_icon: "fa-share-square-o" } %>
    <% end %>
  </div>

app/views/listing/show_post.html.erb
<% title (@comment.commentable.title.titleize + " - " + @comment.commentable.politician.full_name.titleize) %>

  <ol class="breadcrumb">
    <li> <%= link_to @comment.commentable.politician_display.titleize, listing_path(@comment.commentable.politician.id) %></li>
    <li><%= @comment.commentable.title.titleize %></li>
    <li><%= @comment.commentable.location.denorm_name.titleize %></li>
  </ol>

  <div class="container">
    <div class="row container">
      <div class="col-md-6">
        <% if !@comment.pol_image.nil? %> <%= cl_image_tag @comment.pol_image.file_url(:medium), class: "img-responsive" %> <% end %>
        <% if !@comment.external_link.blank? && !@comment.external_link.image_url.blank? %> <img src="<%= @comment.external_link.image_url %>" class="img-responsive" /> <% end %>
      </div>
      <div class="col-md-6">
        <h2>
          <%= @comment.pretty_title.try(:html_safe) %>
        </h2>
        <% unless @comment.external_link.blank? %>
          <a href='<%= @comment.external_link.link_url %>'><%= @comment.external_link.link_url %></a>
        <% end %>
        <% unless @comment.external_link.blank? %>
          <p><%= @comment.external_link.description.try(:html_safe) %></p>
        <% end %>
      </div>
    </div>
    <div class="row container" style="margin-top: 10px;">
      <div class="col-md-12 panel panel-info">
        <small>
          Posted by <%= @comment.user.nil? ? @comment.username_display : link_to(@comment.username_display, users_profile_path(@comment.user.id)) %>
          <span class="badge"><%= @comment.user.cached_score if !@comment.user.nil? %></span>
          on <%= @comment.created_at_pretty %>
          <div class="fb-share-button" data-href="<%= listing_post_url(@comment.commentable.politician_id, @comment.id) %>" data-type="icon"></div>
        </small>

        <div class="panel-body">
          <%= @comment.comment.try(:html_safe)%>
        </div>
      </div>
    </div>

    <h3 class="tab-header"><i class="fa fa-comments"></i> Comments</h3>

    <div id="post_<%= @comment.id %>" class="posts row-striped">
      <%= render partial: "comments", locals: { comment: @comment } %>
    </div>

    <% if user_signed_in? %>
      <%= render partial: "new_comment", locals: { comment: nil, politician: @comment.commentable.politician, c: @comment.commentable, cmt: @comment, visible: true, header_label: "Reply", header_icon: "fa-reply" } %>
    <% end %>
  </div>