config/routes.rb
PhPol::Application.routes.draw do
  devise_for :users, :controllers => {
    :omniauth_callbacks => "users/omniauth_callbacks",
    :registrations => "registrations"
  }

  root :to => "root#index"

  get '/listing', to: 'listing#index', as: :listing_index
  get '/listing/location', to: 'listing#location', as: :listing_location
  get '/listing/:id', to: 'listing#show', as: :listing
  get '/listing/:id/post/:cmt_id', to: 'listing#show_post', as: :listing_post
  post '/listing/:id/vote/:vote', to: 'listing#create_vote', as: :listing_vote_create
  post '/listing/:id/:career_id/image', to: 'listing#create_image', as: :listing_image_create
  post '/listing/location', to: 'listing#create_location_pref', as: :listing_locpref_create

  resources :comment, only: [:show, :create, :destroy]

  namespace :users do
    resources :profile, only: [:edit, :update, :show]
  end

  post 'util/municipal/:id', to: 'util#municipal', as: :util_municipal
  post 'util/pol/', to: 'util#politicians', as: :util_politicians
  get 'util/http_get/', to: 'util#http_get', as: :util_httpget

  

end

app/controllers/root_controller.rb
class RootController < ApplicationController
  def index
    @top_comments = Comment.top_voted.limit(10)
    #@controversial = Career.controversial.limit(10)
    #@active_users = User.with_most_comments.limit(10)

    @tag_posts = []
    if current_user.present?
      user_locs = current_user.locations

      unless user_locs.empty?
        @tag_posts = user_locs.includes(:careers, {careers: [:politician, :comment]}, { careers: { comment: [:pol_image, :external_link] }}).where(comments: { commentable_type: "Career"}).order("comments.created_at")
      end




      @user_votes = current_user.get_votes
    else
      @user_votes = []
    end
  end
end

app/helpers/root_helper.rb
module RootHelper
end

app/views/root/index.html.erb
<% title "Home" %>

<div class="tabs">
<% unless @tag_posts.empty? %>
  <h3 class="tab-header"><i class="fa fa-tags"></i> Tagged</h3>
  <div class="row tab-content">
    <% @tag_posts.first(10).each do |loc| %>
      <% loc.careers.first(5).each do |c| %>
      <% c.comments.first(2).each do |cmt| %>

      <div id="cmt_<%= cmt.id %>" class="col-md-3 col-sm-6 post-box">
        <div href="<%= listing_post_url(c.politician.id, cmt.id) %>" <%= cmt.style_defaults('post-box-img').try(:html_safe) %>>
          <%= render partial: "listing/votes", locals: { cmt: cmt } %>
        </div>
        <ol class="breadcrumb">
          <li><a href="<%= listing_path(c.politician.id) %>"><%= c.politician_display.titleize %></a></li>
          <li><%= c.title.titleize %></li>
          <% unless loc.name.upcase == 'NATIONWIDE' %>
          <li><%= loc.denorm_name.titleize %></li>
          <% end %>
        </ol>
        <div class="subbox">
            <%= link_to trunc(cmt.pretty_title, 40).try(:html_safe), listing_post_url(c.politician.id, cmt.id) %>
            <br/>
            <small>
              by <%= cmt.user.nil? ? cmt.username_display : link_to(cmt.username_display, users_profile_path(cmt.user.id)) %>
              <br/>
              <a href="<%= listing_post_url(c.politician.id, cmt.id) %>" title="<%= pluralize cmt.children.count, "comment" %>">
                <span class="glyphicon glyphicon-comment"></span> <%= cmt.children.count %>
              </a>
              <div class="fb-share-button" data-href="<%= listing_post_url(c.politician.id, cmt.id) %>" data-type="icon" title="Post on Facebook"></div>
            </small>
        </div>
      </div>

      <% end %>
      <% end %>
    <% end %>
  </div>
<% end %>

<% if !@top_comments.blank? %>

  <h3 class="tab-header"><i class="fa fa-flag"></i> Popular</h3>
  <div class="row tab-content">
  <% @top_comments.each do |cmt| %>

    <div id="cmt_<%= cmt.id %>" class="col-md-3 col-sm-6 post-box">
      <div href="<%= listing_post_url(cmt.commentable.politician.id, cmt.id) %>" <%= cmt.style_defaults('post-box-img').try(:html_safe) %>>
        <%= render partial: "listing/votes", locals: { cmt: cmt } %>
      </div>
      <ol class="breadcrumb">
        <li><a href="<%= listing_path(cmt.commentable.politician.id) %>"><%= cmt.commentable.politician_display.titleize %></a></li>
        <li><%= cmt.commentable.title.titleize %></li>
        <% unless cmt.commentable.location.name.upcase == 'NATIONWIDE' %>
        <li><%= cmt.commentable.location.denorm_name.titleize %></li>
        <% end %>
      </ol>

      <div class="subbox">
          <%= link_to trunc(cmt.pretty_title, 40).try(:html_safe), listing_post_url(cmt.commentable.politician.id, cmt.id) %>
          <br/>
          <small>
            by <%= cmt.user.nil? ? cmt.username_display : link_to(cmt.username_display, users_profile_path(cmt.user.id)) %>
            <br/>
            <a href="<%= listing_post_url(cmt.commentable.politician.id, cmt.id) %>" title="<%= pluralize cmt.children.count, "comment" %>">
              <span class="glyphicon glyphicon-comment"></span> <%= cmt.children.count %>
            </a>
            <div class="fb-share-button" data-href="<%= listing_post_url(cmt.commentable.politician.id, cmt.id) %>" data-type="icon" title="Post on Facebook"></div>
          </small>
      </div>

    </div>
  <% end %>
  </div>
<% end %>

</div>