config/routes.rb
PhPol::Application.routes.draw do
  devise_for :users, :controllers => {
    :omniauth_callbacks => "users/omniauth_callbacks",
    :registrations => "registrations"
  }

  root :to => "root#index"

  get '/listing', to: 'listing#index', as: :listing_index
  get '/listing/location', to: 'listing#location', as: :listing_location
  get '/listing/:id', to: 'listing#show', as: :listing
  get '/listing/:id/post/:cmt_id', to: 'listing#show_post', as: :listing_post
  post '/listing/:id/vote/:vote', to: 'listing#create_vote', as: :listing_vote_create
  post '/listing/:id/:career_id/image', to: 'listing#create_image', as: :listing_image_create
  post '/listing/location', to: 'listing#create_location_pref', as: :listing_locpref_create

  resources :comment, only: [:show, :create, :destroy]

  namespace :users do
    resources :profile, only: [:edit, :update, :show]
  end

  post 'util/municipal/:id', to: 'util#municipal', as: :util_municipal
  post 'util/pol/', to: 'util#politicians', as: :util_politicians
  get 'util/http_get/', to: 'util#http_get', as: :util_httpget

  

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= Rails.application.config.site_name + (content_for(:title).nil? ? "" : (" - " + content_for(:title))) %></title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>

  <link rel="shortcut icon" href="<%= asset_path "favicon.ico" %>" >

  <%= yield :head %>

</head>
<body>
<%# Facebook JS SDK %>
<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/en_US/all.js#xfbml=1&appId=<%= Rails.application.config.facebook_app_id %>";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>

<%# JQuery code to make DIVs clicakble %>
<script type="text/javascript">
  $(document).ready(function () {
        $("div[href]").each(function () {
          $(this).css("cursor", "pointer").click(function(e) {
            if ( $(e.target).is($(this)) ) {
              window.location.href = $(this).attr('href');
            }
          });
        });
    });
</script>

<%#-- Logo and Menu bar ----------------------------%>
<div class="navbar navbar-default navbar-static-top" style="margin-bottom: 0px;">
  <div class="container">
    <div class="navbar-header">
      <div class="navbar-brand">
        <a href="/">
          <%= image_tag("site_logo.png", title: Rails.application.config.site_name, height: "21px") %>
          <%= Rails.application.config.site_name %>
        </a>
      </div>
    </div>
    <div class="navbar-collapse collapse navbar-right">
      <ul class="nav navbar-nav">
        <li <%= current_page?(root_path) ? "class=active" : ""%>> <a href="<%= root_path %>"> Home </a> </li>
        <li <%= current_page?(listing_index_path) ? "class=active" : ""%>> <a class="blog-nav-item" href="<%= listing_index_path %>">Search</a> </li>
        <li <%= current_page?(listing_location_path) ? "class=active" : ""%>> <%= link_to "Tag Regions", listing_location_path, "data-no-turbolink" => "true", "class" => "blog-nav-item" %></li>

      <%# user is logged in, show log out link %>
      <% if current_user.present? %>

        <li class="dropdown">
          <a href='#' data-toggle='dropdown'>Profile <b class='caret'></b></a>

          <div class="dropdown-menu" style="padding: 10px 5px;">
            <div class="avatar"><%= current_user.avatar? ? cl_image_tag(current_user.avatar, title: "Profile Pic", alt: current_user.email, width: "64px") : image_tag("empty_avatar.png", title: "Profile Pic") %></div>
            <%= current_user.first_name %> <br/>
            <%= current_user.email %> <br/>
            <%= link_to "edit profile", edit_users_profile_path(current_user) %>
            <div class="divider"></div>
            <%= link_to "Cancel my account", registration_path(:user), data: { confirm:  "Are you sure?" }, method: :delete %>
          </div>
        </li>

        <li>
          <%= link_to "Sign Out", destroy_user_session_path, method: :delete %>
        </li>

      <% else %>

        <li> <%= link_to "Sign Up", new_user_registration_path, "data-no-turbolink" => true %> </li>

        <li class="dropdown">
          <%= link_to new_user_session_path, class: "blog-nav-item", "data-toggle" => "dropdown" do %>
            Sign In
            <b class='caret'></b>
          <% end %>

          <div class="dropdown-menu" style="padding: 10px 5px;">
            <%= form_for("user", :url => user_session_path) do |f| %>
              <%= f.text_field :email, placeholder: "Email", style: "margin-bottom: 5px;" %>
              <%= f.password_field :password, placeholder: "Password", style: "margin-bottom: 5px;" %>

              <%= f.check_box :remember_me %>
              <%= f.label :remember_me, class: "string optional" %>

              <br/>
              <%= f.submit 'Sign in', class: "btn btn-primary" %>

              <br/>
            <% end %>

            <div class="divider"></div>
            <%= link_to "Forgot your password?", new_password_path('user'), "data-no-turbolink" => true %>
            <%= link_to "Sign in with Facebook", user_omniauth_authorize_path(:facebook), "data-no-turbolink" => true %>
          </div>

      <% end %>
      </ul>
    </div>
  </div>
</div>


<div id="flash">
  <% if notice %>
    <script type="text/javascript"> showFlash("<%= escape_javascript(notice)%>"); </script>
  <% end %>
  <% if alert %>
  <div class="flash_alert"><%= alert %></div>
  <% end %>
</div>


<div class="container container-fluid" style="background-color: #FFF;">
  <div id="page_title">
    <h1><%= content_for(:title) %></h1>
  </div>

  <div id="topbody"><%= yield :topbody %></div>

  <div id="mainbody">
    <%= yield %>
  </div>

  <div id="mainfooter">
  </div>
</div>

</body>
</html>